micronaut:
  application:
    name: micronautTeste
datasources:
  default:
    url: jdbc:mysql://localhost:3306/relatorio_condominio_empreendimentos
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: jjbatera4
    schema-generate: CREATE_DROP
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: update
